services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ./config:/config
      #- PATH TO CACHE:/cache
      - type: bind
        #source: PATH TO SOURCES
        target: /media
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # Homepage integration labels
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=https://static-00.iconduck.com/assets.00/jellyfin-icon-2048x2048-tf5ztk6m.png
      - homepage.href=http://192.168.1.15:8096/
      - homepage.description=Media server

